config/routes.rb
Rails.application.routes.draw do

  resources :cities do
    resources :excursions, shallow: true do
      resources :comments, shallow: true
    end
  end

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/city.rb
class City < ApplicationRecord
  has_many :excursions
end

app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :excursion
end

app/models/excursion.rb
class Excursion < ApplicationRecord
  belongs_to :city
  has_many :comments
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/cities_controller.rb
class CitiesController < ApplicationController
  before_action :set_city, only: [:show, :edit, :update, :destroy]

  # GET /cities
  # GET /cities.json
  def index
    @cities = City.all
  end

  # GET /cities/1
  # GET /cities/1.json
  def show
  end

  # GET /cities/new
  def new
    @city = City.new
  end

  # GET /cities/1/edit
  def edit
  end

  # POST /cities
  # POST /cities.json
  def create
    @city = City.new(city_params)

    respond_to do |format|
      if @city.save
        format.html { redirect_to @city, notice: 'City was successfully created.' }
        format.json { render :show, status: :created, location: @city }
      else
        format.html { render :new }
        format.json { render json: @city.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /cities/1
  # PATCH/PUT /cities/1.json
  def update
    respond_to do |format|
      if @city.update(city_params)
        format.html { redirect_to @city, notice: 'City was successfully updated.' }
        format.json { render :show, status: :ok, location: @city }
      else
        format.html { render :edit }
        format.json { render json: @city.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /cities/1
  # DELETE /cities/1.json
  def destroy
    @city.destroy
    respond_to do |format|
      format.html { redirect_to cities_url, notice: 'City was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_city
      @city = City.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def city_params
      params.require(:city).permit(:city)
    end
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  before_action :set_excursion, only: [:show, :edit, :update, :destroy]

  def create
    @excursion = Excursion.find(params[:excursion_id])
    @excursion.comments.create(comment_params)

    redirect_to excursion_path(@excursion)
  end

  def show
  end

  def destroy
    @comment.destroy
    redirect_to :back
  end

 private
    # Use callbacks to share common setup or constraints between actions.
    def set_excursion
      @comment = Comment.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def comment_params
      params.require(:comment).permit(:autor, :body)
    end
end

app/controllers/excursions_controller.rb
class ExcursionsController < ApplicationController
  before_action :set_excursion, only: [:show, :edit, :update, :destroy]

  # GET /excursions
  # GET /excursions.json

  def create
    @city = City.find(params[:city_id])
    @city.excursions.create(excursion_params)

    redirect_to city_path(@city)
  end

  def show
    @excursion = Excursion.find(params[:id])
  end

  def destroy
    @excursion.destroy
    redirect_to :back
  end


  private
    # Use callbacks to share common setup or constraints between actions.
    def set_excursion
      @excursion = Excursion.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def excursion_params
      params.require(:excursion).permit(:title, :phone, :duration, :imgurl, :price, :about)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/cities_helper.rb
module CitiesHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/excursions_helper.rb
module ExcursionsHelper
end

app/views/cities/_form.html.erb
<%= form_for(city) do |f| %>
  <% if city.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(city.errors.count, "error") %> prohibited this city from being saved:</h2>

      <ul>
      <% city.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :city %>
    <%= f.text_area :city %>
  </div>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/cities/edit.html.erb
<h1>Editing City</h1>

<%= render 'form', city: @city %>

<%= link_to 'Show', @city %> |
<%= link_to 'Back', cities_path %>

app/views/cities/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Cities</h1>

<table>
  <thead>
    <tr>
      <th>City</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @cities.each do |city| %>
      <tr>
        <td><%= city.city %></td>
        <td><%= link_to 'Show', city %></td>
        <td><%= link_to 'Edit', edit_city_path(city) %></td>
        <td><%= link_to 'Destroy', city, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New City', new_city_path %>

app/views/cities/new.html.erb
<h1>New City</h1>

<%= render 'form', city: @city %>

<%= link_to 'Back', cities_path %>

app/views/cities/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>City:</strong>
  <%= @city.city %>
</p>

<%= link_to 'Edit', edit_city_path(@city) %> |
<%= link_to 'Back', cities_path %>

<% @city.excursions.each do |excursion| %>
	<hr>
	<p>
	<i><%= excursion.title %> </i><br />
	</p>
	<p>
	<i><%= excursion.phone %> </i><br />
	</p>
	<p>
	<i><%= excursion.duration %> </i><br />
	</p>
	<p>
	<i><%= excursion.title %> </i><br />
	</p>
	<p>
	<i><%= excursion.imgurl %> </i><br />
	</p>
	<p>
	<i><%= excursion.price %> </i><br />
	</p>
	<p>
	<i><%= excursion.about %> </i><br />
	</p>
	<tr>
        <td><%= link_to 'Destroy', excursion_path( excursion ), method: :delete, remote: true, data: { confirm: 'Are you sure?' } %></td>
  </tr>
  	<tr>
        <td><%= link_to 'Show', excursion_path( excursion ) %></td>
  </tr>
<% end %>

<%= form_for([@city, @city.excursions.build]) do |f| %>
	  <div class="field">
    <%= f.label :title %>
    <%= f.text_area :title %>
  </div>

  <div class="field">
    <%= f.label :phone %>
    <%= f.number_field :phone %>
  </div>

  <div class="field">
    <%= f.label :duration %>
    <%= f.number_field :duration %>
  </div>

  <div class="field">
    <%= f.label :imgurl %>
    <%= f.text_area :imgurl %>
  </div>

  <div class="field">
    <%= f.label :price %>
    <%= f.text_field :price %>
  </div>

  <div class="field">
    <%= f.label :about %>
    <%= f.text_area :about %>
  </div>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/excursions/show.html.erb
<strong>Excursion:</strong><br>
  <%= @excursion.title %>
</p>

<% @excursion.comments.each do |comment| %>
	<hr>
	<p>
	<i><%= comment.autor %> </i><br />
	</p>
	<p>
	<i><%= comment.body %> </i><br />
	</p>
  <p>
  <i><%= comment.excursion_id %> </i><br />
  </p>
  <p>
  <i><%= comment.id %> </i><br />
  </p>
   <div>
    <tr>
      <td>
        <%= link_to 'Destroy', comment_path( comment ), method: :delete, remote: true, data: { confirm: 'Are you sure?' } %>
      </td>
    </tr>
  </div>

<% end %>

<%= form_for([@excursion, @excursion.comments.build]) do |f| %>
	  <div class="field">
    <%= f.label :autor %>
    <%= f.text_area :autor %>
  </div>

  <div class="field">
    <%= f.label :body %>
    <%= f.number_field :body %>
  </div>
   <div class="field">
    <%= f.submit %>
  </div>

<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>CityGuide</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>